version: "3"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "8089:8080"
  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
      - SUPERSET_SECRET_KEY=os.urandom(24)
    depends_on:
      - postgres
    ports:
      - "8088:8088"
    volumes:
      - ./superset/superset_config.py:/etc/superset/superset_config.py
